using System.Numerics;
using Content.Shared.Veil.Cult;
using Content.Shared.Teleportation.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Wega.VeilCult.UI;

[GenerateTypedNameReferences]
public sealed partial class TeleportEnchantMenu : DefaultWindow
{
    public string SearchText = "";
    public HashSet<TeleportPoint> Warps = new();

    public event Action<NetEntity>? TeleportClicked;

    public TeleportEnchantMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += OnSearchTextChanged;
    }

    public void UpdateState(TeleportationEnchantBoundUserInterfaceState state)
    {
        Warps = state.Warps;
        AddTeleportButtons();
    }

    public void AddTeleportButtons()
    {
        TeleportButtonContainer.DisposeAllChildren();

        foreach (var points in Warps)
        {
            var name = points.Location;
            var teleportPoint = points.TelePoint;

            var currentButtonRef = new Button
            {
                Text = name,
                TextAlign = Label.AlignMode.Right,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                MinSize = new Vector2(340, 20),
                ClipText = true,
            };

            currentButtonRef.OnPressed += _ => TeleportClicked?.Invoke(teleportPoint);
            currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

            TeleportButtonContainer.AddChild(currentButtonRef);
        }
    }

    private bool ButtonIsVisible(Button button)
    {
        return string.IsNullOrEmpty(SearchText) || button.Text == null ||
               button.Text.Contains(SearchText, StringComparison.OrdinalIgnoreCase);
    }

    private void UpdateVisibleButtons()
    {
        foreach (var child in TeleportButtonContainer.Children)
        {
            if (child is Button button)
                button.Visible = ButtonIsVisible(button);
        }
    }

    public void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        SearchText = args.Text;
        UpdateVisibleButtons();
        // Very funny it's called TeleportScroll
        TeleportScroll.SetScrollValue(Vector2.Zero);
    }
}
