using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Veil.Cult.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VeilBeaconWindow : DefaultWindow
    {
        public event Action<string>? OnNameChanged;

        /// <summary>
        /// Is the user currently entering text into the control?
        /// </summary>
        private bool _focused;
        // TODO LineEdit Make this a bool on the LineEdit control

        private string _name = string.Empty;
        private string _initialName = Loc.GetString("game-ticker-unknown-role");

        public VeilBeaconWindow()
        {
            RobustXamlLoader.Load(this);

            LabelLineEdit.OnTextChanged += e =>
            {
                _name = e.Text;
                OnNameChanged?.Invoke(_name);
                UpdateButtons();
            };

            LabelLineEdit.OnFocusEnter += _ => _focused = true;
            LabelLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                LabelLineEdit.Text = _name;
            };
            ResetNameButton.OnPressed += _ => LabelLineEdit.SetText(_initialName, true);
            ClearNameButton.OnPressed += _ => LabelLineEdit.SetText("", true);
        }

        protected override void Opened()
        {
            base.Opened();

            // Give the editor keyboard focus, since that's the only
            // thing the user will want to be doing with this UI
            LabelLineEdit.GrabKeyboardFocus();
        }

        public void SetCurrentLabel(string name)
        {
            if (name == _name)
                return;

            _name = name;
            if (!_focused)
            {
                LabelLineEdit.Text = name;
                UpdateButtons();
            }
        }

        public void SetInitialNameState()
        {
            LabelLineEdit.Text = _name;
            LabelLineEdit.CursorPosition = _name.Length;
            LabelLineEdit.SelectionStart = 0;
            _initialName = _name;
            UpdateButtons();
        }

        public void UpdateButtons()
        {
            ResetNameButton.Disabled = (LabelLineEdit.Text == _initialName);
            ClearNameButton.Disabled = (LabelLineEdit.Text == "");
        }

        public void SetMaxLabelLength(int maxLength)
        {
            LabelLineEdit.IsValid = s => s.Length <= maxLength;
        }
    }
}
