using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared.Veil.Cult.UI;
using Robust.Shared.GameObjects;

namespace Content.Client.Veil.Cult.Ui;

[GenerateTypedNameReferences]
public sealed partial class VeilAltarMenu : RadialMenu
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    public event Action<EntityUid>? OnSelectEnergy;
    public event Action<EntityUid>? OnSelectOffer;
    
    private EntityUid _user;
    private EntityUid _altar;
    
    public void UpdateState(VeilAltarState state)
    {
        _user = _entMan.GetEntity(state.User);
        _altar = _entMan.GetEntity(state.Altar);
}       

    public VeilAltarMenu()
    {
        RobustXamlLoader.Load(this);
        InitializeButtons();
    }

    private void InitializeButtons()
    {
        EnergyButton.OnButtonUp += _ => HandleEnergySelection();
        OfferButton.OnButtonUp += _ => HandleOfferSelection();
    }

    private void HandleEnergySelection()
    {
        OnSelectEnergy?.Invoke(_user);
        Close();
    }
    private void HandleOfferSelection()
    {
        OnSelectOffer?.Invoke(_altar);
        Close();
    }
}
