using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.VeilCult.UI;

[GenerateTypedNameReferences]
public sealed partial class VeilAltarMenu : RadialMenu
{
    public event Action? OnSelectEnergy;
    public event Action? OnSelectOffer;

    public VeilAltarMenu()
    {
        RobustXamlLoader.Load(this);

        EnergyButton.OnButtonUp += _ => OnSelectEnergy?.Invoke();
        OfferButton.OnButtonUp += _ => OnSelectOffer?.Invoke();
    }
}
