[game]
hostname = "🌟 Corvax — Вега 🌟[TTS][18+]"
desc = "Корвакс — первый русскоязычный проект в Space Station 14.\nВега — первый официальный ЕРП сервер от Корвакс, где ЕРП — это не обязательный элемент, а опция для тех, кто хочет добавить глубины в свою игру.\nНа Вега внедрён TTS (Text-to-Speech), чтобы сделать общение более живым и атмосферным."
map_pool = "WegaDefaultMapPool"
secret_weight_prototype = "WegaSecretDefault"
maxplayers = 180
soft_max_players = 100
lobbyduration = 360
map_rotation = false

[events]
enabled = true

[wega]
respawn_enabled = true
barks_enabled = true
night_light_enabled = true
roundend_vote_enabled = true
sound_insulation_enabled = true

[net]
tickrate = 30

[netres]
limit = 25.0

[admin]
admins_count_in_playercount = true

[movement]
mob_pushing = false

[infolinks]
discord = "https://discord.gg/bJrgSmKf3a"
wiki = "https://station14.ru"
appeal = "https://discord.gg/bJrgSmKf3a"
website = "https://ss14.ru"
patreon = "https://boosty.to/corvaxwega"

[viewport]
maximum_width = 26

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 0
min_overall_minutes = 0
deny_vpn = true
enable_without_admins = true
disable_with_admins = true

[rules]
time = 180.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e,tts,18+"

[server]
lobby_name = "🌟 Corvax — Вега 🌟[TTS][18+]"
rules_file = "WegaRuleset"

[atmos]
max_explosion_range = 5
space_wind = true

[shuttle]
emergency_early_launch_allowed = true
arrivals_map = "/Maps/Corvax/Misc/corvax_terminal.yml"
auto_call_time = 150

[vote]
preset_enabled = false
timerpreset = 240
map_enabled = true
