using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementNotification : PanelContainer
{
    public AchievementNotification()
    {
        RobustXamlLoader.Load(this);
    }

    public void Show(string name, string description, Texture? icon)
    {
        NotificationName.Text = name;
        NotificationDescription.SetMessage(description);
        NotificationIcon.Texture = icon;

        NotificationRoot.Visible = true;
    }
}
