using Content.Shared.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementEntry : Button
{
    public AchievementEntry(AchievementPrototype prototype, bool isUnlocked, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        var spriteSpecifier = prototype.AchievementIcon;
        AchievementIcon.Texture = sprite.Frame0(spriteSpecifier);

        AchievementName.Text = Loc.GetString(prototype.Name);

        AchievementStatus.Text = isUnlocked
            ? Loc.GetString("ui-achievements-unlocked")
            : Loc.GetString("ui-achievements-locked");
        AchievementStatus.FontColorOverride = isUnlocked ? Color.Gold : Color.Gray;

        if (prototype.Description != null)
        {
            var description = Loc.GetString(prototype.Description);
            AchievementDescription.SetMessage(description);
        }

        Container.OnPressed += args => SetSelected(true);
    }

    public void SetSelected(bool selected)
    {
        Container.Pressed = selected;

        if (selected)
        {
            Container.StyleClasses.Add("ButtonOpenBoth");
        }
        else
        {
            Container.StyleClasses.Remove("ButtonOpenBoth");
        }
    }
}
