using System.Linq;
using Content.Client.Achievements;
using Content.Client.UserInterface.Controls;
using Content.Shared.Achievements;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Wega.Achievements;

[GenerateTypedNameReferences]
public sealed partial class AchievementsWindow : FancyWindow
{
    [Dependency] private readonly IDependencyCollection _dependencies = default!;
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private readonly AchievementsSystem _achievements;
    private readonly SpriteSystem _spriteSystem;

    private readonly Dictionary<AchievementsEnum, AchievementEntry> _entries = new();
    private List<AchievementPrototype> _allAchievements = new();

    public AchievementsWindow()
    {
        RobustXamlLoader.Load(this);
        _dependencies.InjectDependencies(this);
        _achievements = _sysMan.GetEntitySystem<AchievementsSystem>();
        _spriteSystem = _sysMan.GetEntitySystem<SpriteSystem>();

        _achievements.OnAchievementsUpdated += OnAchievementsUpdated;

        LoadAchievements();
    }

    private void LoadAchievements()
    {
        _allAchievements = _prototypeManager.EnumeratePrototypes<AchievementPrototype>().ToList();
        _achievements.RequestAchievements();

        UpdateAchievements(new List<AchievementsEnum>(), _allAchievements);
    }

    private void OnAchievementsUpdated()
    {
        var unlocked = _achievements.UnlockedAchievements.ToList();
        UpdateAchievements(unlocked, _allAchievements);
    }

    public void UpdateAchievements(List<AchievementsEnum> unlockedAchievements, List<AchievementPrototype> allAchievements)
    {
        AchievementsList.RemoveAllChildren();
        _entries.Clear();

        int total = allAchievements.Count;
        int unlocked = unlockedAchievements.Count;

        ProgressLabel.Text = total > 0 ? $"{unlocked * 100 / total}%" : "0%";

        var sortedAchievements = allAchievements
            .OrderByDescending(a => unlockedAchievements.Contains(a.Key))
            .ThenBy(a => a.Key).ToList();

        foreach (var achievementProto in sortedAchievements)
        {
            var isUnlocked = unlockedAchievements.Contains(achievementProto.Key);

            var entry = new AchievementEntry(achievementProto, isUnlocked, _spriteSystem);
            AchievementsList.AddChild(entry);

            _entries[achievementProto.Key] = entry;

            entry.OnPressed += _ =>
            {
                SelectAchievement(achievementProto, isUnlocked);

                foreach (var otherEntry in _entries.Values)
                {
                    if (otherEntry != entry)
                    {
                        otherEntry.SetSelected(false);
                    }
                }

                entry.SetSelected(true);
            };
        }

        SelectedAchievementPanel.Visible = false;
    }

    private void SelectAchievement(AchievementPrototype prototype, bool isUnlocked)
    {
        SelectedAchievementPanel.Visible = true;

        if (isUnlocked)
        {
            var spriteSpecifier = prototype.AchievementIcon;
            SelectedIcon.Texture = _spriteSystem.Frame0(spriteSpecifier);
        }
        else
        {
            var lockedSprite = new SpriteSpecifier.Rsi(new ResPath("/Textures/_Wega/Interface/achievements.rsi"), "locked");
            SelectedIcon.Texture = _spriteSystem.Frame0(lockedSprite);
        }

        SelectedName.Text = Loc.GetString(prototype.Name);

        if (prototype.Description != null)
        {
            var description = Loc.GetString(prototype.Description);
            SelectedDescription.SetMessage(description);
        }

        SelectedStatus.Text = isUnlocked
            ? Loc.GetString("ui-achievements-unlocked")
            : Loc.GetString("ui-achievements-locked");
        SelectedStatus.FontColorOverride = isUnlocked ? Color.Gold : Color.Gray;
    }
}
