- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 #20h
  startingGear: PrisonerGear
  icon: "JobIconPrisoner"
  canBeAntag: false
  RoleType: FreeAgent

- type: startingGear
  id: PrisonerGear
  equipment:
    id: PrisonerIDCard
    ears: ClothingHeadsetGrey
    shoes: ClothingShoesColorBrown
