using Content.Client.UserInterface.Controls;
using Content.Shared._Wega.Ninja;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._Wega.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class MindScanMachineWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;

    public event Action? OnScan;
    public event Action? OnEject;
    public event Action? OnTeleport;

    public MindScanMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ScanButton.OnPressed     += _ => OnScan?.Invoke();
        EjectButton.OnPressed    += _ => OnEject?.Invoke();
        TeleportButton.OnPressed += _ => OnTeleport?.Invoke();
    }

    public void UpdateState(MindScanMachineBuiState state)
    {
        var hasOccupant = state.Occupant != null;
        var entity = hasOccupant ? (EntityUid?) _entityManager.GetEntity(state.Occupant!.Value) : null;

        if (entity != null && _entityManager.EntityExists(entity.Value))
        {
            OccupantSprite.SetEntity(entity);
            OccupantSprite.Visible = true;

            OccupantNameLabel.Text = _entityManager.TryGetComponent<MetaDataComponent>(entity.Value, out var meta)
                ? meta.EntityName
                : Loc.GetString("mind-scan-machine-unknown");

            OccupantStatusLabel.Text = state.IsAlive
                ? Loc.GetString("mind-scan-machine-status-alive")
                : Loc.GetString("mind-scan-machine-status-dead");

            OccupantStatusLabel.FontColorOverride = state.IsAlive ? Color.LimeGreen : Color.Red;

            OccupantDamageLabel.Text = $"{(int) state.TotalDamage} {Loc.GetString("mind-scan-machine-damage-unit")}";
        }
        else
        {
            OccupantSprite.SetEntity(null);
            OccupantSprite.Visible = false;
            OccupantNameLabel.Text = Loc.GetString("mind-scan-machine-no-patient");
            OccupantStatusLabel.Text = "—";
            OccupantStatusLabel.FontColorOverride = null;
            OccupantDamageLabel.Text = "—";
        }

        ScanButton.Disabled     = !hasOccupant || state.IsScanning || state.ScanComplete;
        TeleportButton.Disabled = !state.ScanComplete;
        EjectButton.Disabled    = !hasOccupant;

        if (state.IsScanning)
        {
            ScanButton.Text = Loc.GetString("mind-scan-machine-button-scanning");
        }
        else
        {
            ScanButton.Text = Loc.GetString("mind-scan-machine-button-scan");
        }

        ScannedList.RemoveAllChildren();
        if (state.ScannedNames.Count == 0)
        {
            ScannedList.AddChild(new Label
            {
                Text = Loc.GetString("mind-scan-machine-no-scanned"),
                FontColorOverride = Color.Gray,
            });
        }
        else
        {
            foreach (var name in state.ScannedNames)
            {
                ScannedList.AddChild(new Label { Text = $"• {name}" });
            }
        }
    }
}
