using Content.Client.UserInterface.Controls;
using Content.Shared._Wega.Ninja;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;

namespace Content.Client._Wega.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class NinjaBloodScanMachineWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action<int>? OnSlotAction;
    public event Action? OnScan;

    // Slot state panel colours — match SS13 NoticeBox colour scheme:
    // NotDone (2) = dark blue, Success (1) = dark green, Failed (0) = dark red
    private static readonly StyleBoxFlat PanelNotDone  = new(Color.FromHex("#0d1a36"));
    private static readonly StyleBoxFlat PanelSuccess  = new(Color.FromHex("#0a2e10"));
    private static readonly StyleBoxFlat PanelFailed   = new(Color.FromHex("#2e0a0a"));
    private static readonly StyleBoxFlat PanelScanRow  = new(Color.FromHex("#2e0a0a"));

    public NinjaBloodScanMachineWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Slot0Button.OnPressed += _ => OnSlotAction?.Invoke(0);
        Slot1Button.OnPressed += _ => OnSlotAction?.Invoke(1);
        Slot2Button.OnPressed += _ => OnSlotAction?.Invoke(2);
        ScanButton.OnPressed  += _ => OnScan?.Invoke();

        // Red panel behind the scan button (mirrors SS13 NoticeBox_red)
        ScanRowPanel.PanelOverride = PanelScanRow;
    }

    public void UpdateState(NinjaBloodScanBuiState state)
    {
        UpdateSlot(0, state);
        UpdateSlot(1, state);
        UpdateSlot(2, state);

        ScanButton.Disabled = state.BlockButtons;
        ScanButton.Text = state.BlockButtons
            ? Loc.GetString("ninja-blood-scan-button-scanning")
            : Loc.GetString("ninja-blood-scan-button-scan");

        ScanProgressBar.Value = state.ProgressBar;
        ProgressLabel.Text = state.ProgressBar > 0
            ? Loc.GetString("ninja-blood-scan-progress-loading", ("percent", state.ProgressBar))
            : Loc.GetString("ninja-blood-scan-progress-idle");
    }

    private void UpdateSlot(int idx, NinjaBloodScanBuiState state)
    {
        var (title, panel, sprite, nameLabel, button) = idx switch
        {
            0 => (Slot0Title, Slot0Panel, Slot0Sprite, Slot0Name, Slot0Button),
            1 => (Slot1Title, Slot1Panel, Slot1Sprite, Slot1Name, Slot1Button),
            _ => (Slot2Title, Slot2Panel, Slot2Sprite, Slot2Name, Slot2Button),
        };

        var hasVial    = state.DonorNames[idx] != null;
        var scanState  = state.ScanStates[idx]; // 0=Failed, 1=Success, 2=NotDone

        // Slot title mirrors SS13: "Кровь" / "Нет реагента"
        title.Text = hasVial
            ? Loc.GetString("ninja-blood-scan-slot-blood")
            : Loc.GetString("ninja-blood-scan-slot-empty");

        // Panel background — matches SS13 NoticeBox_red / default / NoticeBox_blue
        panel.PanelOverride = scanState switch
        {
            0 => PanelFailed,
            1 => PanelSuccess,
            _ => PanelNotDone,
        };

        // Vial sprite
        if (state.VialEntities[idx] is { } netEntity)
        {
            var uid = _entityManager.GetEntity(netEntity);
            sprite.SetEntity(_entityManager.EntityExists(uid) ? uid : (EntityUid?) null);
        }
        else
        {
            sprite.SetEntity(null);
        }

        // Donor name label
        nameLabel.Text = state.DonorNames[idx] ?? "—";

        // Eject button is only active when a vial is present and scan is not running
        button.Disabled = !hasVial || state.BlockButtons;
    }
}
