using Content.Client.UserInterface.Controls;
using Content.Shared._Wega.Ninja;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class NinjaTeleConsoleWindow : FancyWindow
{
    public event Action? OnConfirm;
    public event Action? OnCancel;

    public NinjaTeleConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => OnConfirm?.Invoke();
        CancelButton.OnPressed  += _ => OnCancel?.Invoke();
    }

    public void UpdateState(NinjaTeleConsoleBuiState state)
    {
        if (state.PlayerNearbyAtDestination)
        {
            WarningLabel.Visible = true;
            WarningLabel.Text = Loc.GetString("ninja-teleconsole-warning");
        }
        else
        {
            WarningLabel.Visible = false;
        }
    }
}
