- type: gameMapPool
  id: WegaDefaultMapPool
  maps:
  # Highpop
  - WegaKerberos
  - WegaCereStation
  - WegaSpectrum
  - WegaEmerald
  - WegaFland
  # Midpop
  - WegaCyberiad
  - WegaIshimura
  - WegaKilo
  - WegaCore
  - WegaBagel
  - WegaMarathon
  # Lowpop
  - WegaSilly
  - WegaTuhoba
  - WegaBarratry
  - WegaPacked
  - WegaMeta
