using System.Numerics;
using Content.Shared.Martial.Arts.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Wega.MartialArts.UI;

[GenerateTypedNameReferences]
public sealed partial class ComboVisualizationWidget : UIWidget
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPlayerManager _player = default!;

    private SpriteSystem? _sprite;
    private int _lastCount = -1;

    private bool _dragging;
    private Vector2 _dragOffset;

    private const int IconSize = 32;
    private const int IconGap = 4;

    public ComboVisualizationWidget()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        MouseFilter = MouseFilterMode.Stop;
        LayoutContainer.SetGrowHorizontal(this, LayoutContainer.GrowDirection.Begin);
        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = true;
        _dragOffset = args.PointerLocation.Position / UIScale - Position;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragging = false;
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);
        if (!_dragging || Parent == null)
            return;

        var newPos = args.GlobalPosition - _dragOffset;
        newPos = Vector2.Clamp(newPos, Vector2.Zero, Parent.Size - Size);
        LayoutContainer.SetPosition(this, newPos);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var localEnt = _player.LocalEntity;
        int count = 0;
        List<string>? icons = null;

        if (localEnt != null
            && _entMan.TryGetComponent<ComboVisualizationComponent>(localEnt.Value, out var comp))
        {
            icons = comp.Icons;
            count = icons.Count;
        }

        if (count == _lastCount)
            return;

        _lastCount = count;
        IconContainer.RemoveAllChildren();

        if (count == 0)
            return;

        _sprite ??= _entMan.System<SpriteSystem>();
        foreach (var icon in icons!)
        {
            var spec = new SpriteSpecifier.Rsi(
                new ResPath("/Textures/_Wega/Interface/intents.rsi"), icon);
            IconContainer.AddChild(new TextureRect
            {
                Texture = _sprite.Frame0(spec),
                SetSize = new Vector2(IconSize, IconSize),
                Stretch = TextureRect.StretchMode.Scale,
            });
        }
    }
}
