using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Wega.BloodCult.Ui;

[GenerateTypedNameReferences]
public sealed partial class BloodRitesMenu : RadialMenu
{
    public event Action<EntProtoId>? OnSelectRites;

    public BloodRitesMenu()
    {
        RobustXamlLoader.Load(this);
        InitializeButtons();
    }

    private void InitializeButtons()
    {
        BloodOrbButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultOrb");
        BloodRechargeButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultRecharge");
        BloodSpearButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultSpear");
        BloodBoltBarrageButton.OnButtonUp += _ => HandleRitesSelection("ActionBloodCultBoltBarrage");
    }

    private void HandleRitesSelection(EntProtoId rites)
    {
        OnSelectRites?.Invoke(rites);
        Close();
    }
}
