using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Wega.BloodCult.Ui;

[GenerateTypedNameReferences]
public sealed partial class BloodMagicMenu : RadialMenu
{
    public event Action<EntProtoId>? OnSelectedSpell;

    public BloodMagicMenu()
    {
        RobustXamlLoader.Load(this);
        InitializeButtons();
    }

    private void InitializeButtons()
    {
        StunButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultStun");
        TeleportButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultTeleport");
        ElectromagneticPulseButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultElectromagneticPulse");
        ShadowShacklesButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultShadowShackles");
        TwistedConstructionButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultTwistedConstruction");
        SummonEquipmentButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultSummonEquipment");
        SummonDaggerButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultSummonDagger");
        HallucinationsButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultHallucinations");
        ConcealPresenceButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultConcealPresence");
        BloodRitesButton.OnButtonUp += _ => HandleSpellSelection("ActionBloodCultBloodRites");
    }

    private void HandleSpellSelection(EntProtoId spell)
    {
        OnSelectedSpell?.Invoke(spell);
    }
}

