using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Wega.BloodCult.Ui;

[GenerateTypedNameReferences]
public sealed partial class RunesMenu : RadialMenu
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<EntProtoId>? OnRuneSelected;

    public RunesMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.Instance!.InjectDependencies(this);
        InitializeRunes();
    }

    private void InitializeRunes()
    {
        AddRuneButton("offering-rune", "BloodRuneOffering");
        AddRuneButton("teleport-rune", "BloodRuneTeleport");
        AddRuneButton("empowering-rune", "BloodRuneEmpowering");
        AddRuneButton("revive-rune", "BloodRuneRevive");
        AddRuneButton("barrier-rune", "BloodRuneBarrier");
        AddRuneButton("summoning-rune", "BloodRuneSummoning");
        AddRuneButton("bloodboil-rune", "BloodRuneBloodBoil");
        AddRuneButton("spiritrealm-rune", "BloodRuneSpiritealm");
    }

    public void AddRitualButton()
    {
        AddRuneButton("ritual-dimensional-rending-rune", "BloodRuneRitualDimensionalRending");
    }

    private void AddRuneButton(string runeName, string protoId)
    {
        if (!_proto.TryIndex(protoId, out var prototype))
            return;

        var button = new RadialMenuButton
        {
            ToolTip = Loc.GetString(runeName) + $"\n{Loc.GetString(runeName + "-desc")}",
            SetSize = new Vector2(64, 64),
        };

        button.StyleClasses.Add("RadialMenuButton");

        var entityView = new EntityPrototypeView
        {
            Scale = new Vector2(2, 2),
            SetSize = new Vector2(64, 64),
            Margin = new Thickness(4)
        };
        entityView.SetPrototype(prototype.ID);

        button.AddChild(entityView);

        button.OnPressed += _ => HandleRuneSelection(protoId);

        Main.AddChild(button);
    }

    private void HandleRuneSelection(EntProtoId protoId)
    {
        OnRuneSelected?.Invoke(protoId);
        Close();
    }
}
