using Content.Client.UserInterface.Controls;
using Content.Shared.Lavaland;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Wega.Lavaland;

[GenerateTypedNameReferences]
public sealed partial class LavalandConsoleWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    public Action? OnCallButtonPressed;
    private TimeSpan? _cooldownEndTime;

    public LavalandConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        CallButton.OnPressed += _ => OnCallButtonPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCooldownInfo();
    }

    public void UpdateState(LavalandShuttleConsoleState state)
    {
        _cooldownEndTime = state.NextLaunchTime;

        var statusText = state.Status switch
        {
            ShuttleStatus.DockedAtStation => Loc.GetString("lavaland-shuttle-status-docked-station"),
            ShuttleStatus.DockedAtOutpost => Loc.GetString("lavaland-shuttle-status-docked-outpost"),
            ShuttleStatus.EnRouteToStation => Loc.GetString("lavaland-shuttle-status-enroute-station"),
            ShuttleStatus.EnRouteToOutpost => Loc.GetString("lavaland-shuttle-status-enroute-outpost"),
            _ => Loc.GetString("lavaland-shuttle-status-unknown")
        };
        StatusLabel.Text = statusText;

        var locationText = state.Location switch
        {
            DockLocation.Station => Loc.GetString("lavaland-shuttle-location-station"),
            DockLocation.Outpost => Loc.GetString("lavaland-shuttle-location-outpost"),
            DockLocation.Shuttle => Loc.GetString("lavaland-shuttle-location-shuttle"),
            _ => Loc.GetString("lavaland-shuttle-location-unknown")
        };
        LocationLabel.Text = locationText;

        UpdateCallButton(state);
        UpdateStatusVisuals(state.Status, state.Location);
        UpdateCooldownInfo();
    }

    private void UpdateCallButton(LavalandShuttleConsoleState state)
    {
        var isOnCooldown = _cooldownEndTime.HasValue && _gameTiming.CurTime < _cooldownEndTime.Value;

        if (isOnCooldown)
        {
            CallButton.Disabled = true;
            CallButton.Text = Loc.GetString("lavaland-shuttle-on-cooldown");
        }
        else
        {
            CallButton.Disabled = !state.CanCallShuttle;
            CallButton.Text = GetButtonText(state);
        }

        CallButton.ModulateSelfOverride = isOnCooldown
            ? Color.FromHex("#6D4C41")
            : state.CanCallShuttle
                ? GetActiveButtonColor(state)
                : Color.FromHex("#546E7A");
    }

    private string GetButtonText(LavalandShuttleConsoleState state)
    {
        if (!state.CanCallShuttle)
            return Loc.GetString("lavaland-shuttle-call-unavailable");

        return state.Status switch
        {
            ShuttleStatus.DockedAtStation => Loc.GetString("lavaland-shuttle-call-to-outpost"),
            ShuttleStatus.DockedAtOutpost => Loc.GetString("lavaland-shuttle-recall-to-station"),
            _ => Loc.GetString("lavaland-shuttle-call-unavailable")
        };
    }

    private void UpdateCooldownInfo()
    {
        if (_cooldownEndTime.HasValue)
        {
            var timeLeft = _cooldownEndTime.Value - _gameTiming.CurTime;
            if (timeLeft > TimeSpan.Zero)
            {
                InfoLabel.Text = Loc.GetString("lavaland-shuttle-cooldown-time",
                    ("time", FormatTime(timeLeft)));
                InfoLabel.FontColorOverride = Color.FromHex("#FF9800");
            }
            else
            {
                _cooldownEndTime = null;
                InfoLabel.Text = Loc.GetString("lavaland-shuttle-info-ready");
                InfoLabel.FontColorOverride = Color.FromHex("#4CAF50");
            }
        }
        else
        {
            _cooldownEndTime = null;
            InfoLabel.Text = Loc.GetString("lavaland-shuttle-info-ready");
            InfoLabel.FontColorOverride = Color.FromHex("#4CAF50");
        }
    }

    private void UpdateStatusVisuals(ShuttleStatus status, DockLocation location)
    {
        var statusColor = status switch
        {
            ShuttleStatus.DockedAtStation => Color.FromHex("#4CAF50"),
            ShuttleStatus.DockedAtOutpost => Color.FromHex("#2196F3"),
            ShuttleStatus.EnRouteToStation => Color.FromHex("#FF9800"),
            ShuttleStatus.EnRouteToOutpost => Color.FromHex("#FF5722"),
            _ => Color.FromHex("#F44336")
        };

        StatusLabel.FontColorOverride = statusColor;

        LocationLabel.FontColorOverride = location switch
        {
            DockLocation.Station => Color.FromHex("#81C784"),
            DockLocation.Outpost => Color.FromHex("#64B5F6"),
            DockLocation.Shuttle => Color.FromHex("#FFB74D"),
            _ => Color.White
        };
    }

    private Color GetActiveButtonColor(LavalandShuttleConsoleState state)
    {
        return (state.Location, state.Status) switch
        {
            (DockLocation.Station, _) or
            (DockLocation.Shuttle, ShuttleStatus.DockedAtStation)
                => Color.FromHex("#FF5722"),

            (DockLocation.Outpost, _) or
            (DockLocation.Shuttle, ShuttleStatus.DockedAtOutpost)
                => Color.FromHex("#2196F3"),

            _ => Color.FromHex("#4CAF50")
        };
    }

    private static string FormatTime(TimeSpan timeSpan)
    {
        if (timeSpan.TotalMinutes >= 1)
        {
            return $"{(int)timeSpan.TotalMinutes}:{timeSpan.Seconds:00}";
        }
        return timeSpan.ToString(@"ss\s");
    }
}
