
using Content.Client.UserInterface.Controls;
using Content.Shared.Lavaland;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Wega.Lavaland;

[GenerateTypedNameReferences]
public sealed partial class LavalandConsoleWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    public Action? OnCallButtonPressed;

    public LavalandConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CallButton.OnPressed += _ => OnCallButtonPressed?.Invoke();
    }

    public void UpdateState(LavalandShuttleConsoleState state)
    {
        var statusText = state.Status switch
        {
            ShuttleStatus.DockedAtStation => Loc.GetString("lavaland-shuttle-status-docked-station"),
            ShuttleStatus.DockedAtOutpost => Loc.GetString("lavaland-shuttle-status-docked-outpost"),
            ShuttleStatus.EnRouteToStation => Loc.GetString("lavaland-shuttle-status-enroute-station"),
            ShuttleStatus.EnRouteToOutpost => Loc.GetString("lavaland-shuttle-status-enroute-outpost"),
            _ => Loc.GetString("lavaland-shuttle-status-unknown")
        };
        StatusLabel.Text = statusText;

        // Таймер
        if (state.NextLaunchTime.HasValue)
        {
            var timeLeft = state.NextLaunchTime.Value - _gameTiming.CurTime;
            TimerLabel.Text = Loc.GetString("lavaland-shuttle-time-remaining",
                ("time", timeLeft.ToString(@"mm\:ss")));
            TimerLabel.Visible = true;
        }
        else
        {
            TimerLabel.Visible = false;
        }

        // Кнопка вызова
        CallButton.Disabled = !state.CanCallShuttle;
        CallButton.Text = state.Location switch
        {
            DockLocation.Station => Loc.GetString("lavaland-shuttle-call-to-outpost"),
            DockLocation.Outpost => Loc.GetString("lavaland-shuttle-recall-to-station"),
            DockLocation.Shuttle when state.Status == ShuttleStatus.DockedAtStation =>
                Loc.GetString("lavaland-shuttle-call-to-outpost"),
            DockLocation.Shuttle when state.Status == ShuttleStatus.DockedAtOutpost =>
                Loc.GetString("lavaland-shuttle-recall-to-station"),
            _ => Loc.GetString("lavaland-shuttle-call-unavailable")
        };

        UpdateStatusVisuals(state.Status);
    }

    private void UpdateStatusVisuals(ShuttleStatus status)
    {
        var color = status switch
        {
            ShuttleStatus.DockedAtStation or ShuttleStatus.DockedAtOutpost => Color.FromHex("#4E9A06"),
            ShuttleStatus.EnRouteToStation or ShuttleStatus.EnRouteToOutpost => Color.FromHex("#CE5C00"),
            _ => Color.FromHex("#CC0000")
        };

        StatusLabel.FontColorOverride = color;
        StatusPanel.ModulateSelfOverride = color.WithAlpha(0.1f);
    }
}
