using Content.Client.UserInterface.Controls;
using Content.Shared.Lavaland;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Wega.Lavaland;

[GenerateTypedNameReferences]
public sealed partial class LavalandPenalServitudeConsoleWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    public Action? OnCallButtonPressed;
    private TimeSpan? _cooldownEndTime;

    public LavalandPenalServitudeConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        CallButton.OnPressed += _ => OnCallButtonPressed?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateCooldownInfo();
    }

    public void UpdateState(PenalServitudeLavalandShuttleConsoleState state)
    {
        _cooldownEndTime = state.NextLaunchTime;

        var statusText = state.Status switch
        {
            PenalServitudeLavalandShuttleStatus.DockedAtStation => Loc.GetString("prison-shuttle-status-docked-station"),
            PenalServitudeLavalandShuttleStatus.DockedAtPenalServitude => Loc.GetString("prison-shuttle-status-docked-prison"),
            PenalServitudeLavalandShuttleStatus.EnRouteToStation => Loc.GetString("prison-shuttle-status-enroute-station"),
            PenalServitudeLavalandShuttleStatus.EnRouteToPenalServitude => Loc.GetString("prison-shuttle-status-enroute-prison"),
            _ => Loc.GetString("prison-shuttle-status-unknown")
        };
        StatusLabel.Text = statusText;

        var locationText = state.Location switch
        {
            PenalServitudeLavalandDockLocation.Station => Loc.GetString("prison-shuttle-location-station"),
            PenalServitudeLavalandDockLocation.PenalServitude => Loc.GetString("prison-shuttle-location-prison"),
            PenalServitudeLavalandDockLocation.Shuttle => Loc.GetString("prison-shuttle-location-shuttle"),
            _ => Loc.GetString("prison-shuttle-location-unknown")
        };
        LocationLabel.Text = locationText;

        UpdateCallButton(state);
        UpdateStatusVisuals(state.Status, state.Location);
        UpdateCooldownInfo();
    }

    private void UpdateCallButton(PenalServitudeLavalandShuttleConsoleState state)
    {
        var isOnCooldown = _cooldownEndTime.HasValue && _gameTiming.CurTime < _cooldownEndTime.Value;

        if (isOnCooldown)
        {
            CallButton.Disabled = true;
            CallButton.Text = Loc.GetString("prison-shuttle-on-cooldown");
        }
        else
        {
            CallButton.Disabled = !state.CanCallShuttle;
            CallButton.Text = GetButtonText(state);
        }

        CallButton.ModulateSelfOverride = isOnCooldown
            ? Color.FromHex("#6D4C41")
            : state.CanCallShuttle
                ? GetActiveButtonColor(state)
                : Color.FromHex("#546E7A");
    }

    private string GetButtonText(PenalServitudeLavalandShuttleConsoleState state)
    {
        if (!state.CanCallShuttle)
            return Loc.GetString("prison-shuttle-call-unavailable");

        return state.Status switch
        {
            PenalServitudeLavalandShuttleStatus.DockedAtStation => Loc.GetString("prison-shuttle-call-to-prison"),
            PenalServitudeLavalandShuttleStatus.DockedAtPenalServitude => Loc.GetString("prison-shuttle-recall-to-station"),
            _ => Loc.GetString("prison-shuttle-call-unavailable")
        };
    }

    private void UpdateCooldownInfo()
    {
        if (_cooldownEndTime.HasValue)
        {
            var timeLeft = _cooldownEndTime.Value - _gameTiming.CurTime;
            if (timeLeft > TimeSpan.Zero)
            {
                InfoLabel.Text = Loc.GetString("prison-shuttle-cooldown-time",
                    ("time", FormatTime(timeLeft)));
                InfoLabel.FontColorOverride = Color.FromHex("#FF9800");
            }
            else
            {
                _cooldownEndTime = null;
                InfoLabel.Text = Loc.GetString("prison-shuttle-info-ready");
                InfoLabel.FontColorOverride = Color.FromHex("#4CAF50");
            }
        }
        else
        {
            _cooldownEndTime = null;
            InfoLabel.Text = Loc.GetString("prison-shuttle-info-ready");
            InfoLabel.FontColorOverride = Color.FromHex("#4CAF50");
        }
    }

    private void UpdateStatusVisuals(PenalServitudeLavalandShuttleStatus status, PenalServitudeLavalandDockLocation location)
    {
        var statusColor = status switch
        {
            PenalServitudeLavalandShuttleStatus.DockedAtStation => Color.FromHex("#4CAF50"),
            PenalServitudeLavalandShuttleStatus.DockedAtPenalServitude => Color.FromHex("#F44336"),
            PenalServitudeLavalandShuttleStatus.EnRouteToStation => Color.FromHex("#FF9800"),
            PenalServitudeLavalandShuttleStatus.EnRouteToPenalServitude => Color.FromHex("#FF5722"),
            _ => Color.FromHex("#F44336")
        };

        StatusLabel.FontColorOverride = statusColor;

        LocationLabel.FontColorOverride = location switch
        {
            PenalServitudeLavalandDockLocation.Station => Color.FromHex("#81C784"),
            PenalServitudeLavalandDockLocation.PenalServitude => Color.FromHex("#EF5350"),
            PenalServitudeLavalandDockLocation.Shuttle => Color.FromHex("#FFB74D"),
            _ => Color.White
        };
    }

    private Color GetActiveButtonColor(PenalServitudeLavalandShuttleConsoleState state)
    {
        return (state.Location, state.Status) switch
        {
            (PenalServitudeLavalandDockLocation.Station, _) or
            (PenalServitudeLavalandDockLocation.Shuttle, PenalServitudeLavalandShuttleStatus.DockedAtStation)
                => Color.FromHex("#F44336"),

            (PenalServitudeLavalandDockLocation.PenalServitude, _) or
            (PenalServitudeLavalandDockLocation.Shuttle, PenalServitudeLavalandShuttleStatus.DockedAtPenalServitude)
                => Color.FromHex("#2196F3"),

            _ => Color.FromHex("#4CAF50")
        };
    }

    private static string FormatTime(TimeSpan timeSpan)
    {
        if (timeSpan.TotalMinutes >= 1)
        {
            return $"{(int)timeSpan.TotalMinutes}:{timeSpan.Seconds:00}";
        }
        return timeSpan.ToString(@"ss\s");
    }
}
