using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.FixedPoint;
using Content.Shared.Lavaland;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Wega.Lavaland;

[GenerateTypedNameReferences]
public sealed partial class UtilityVendorMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IDependencyCollection _dependencies = default!;

    public event Action<string>? OnPurchase;

    public UtilityVendorMenu()
    {
        RobustXamlLoader.Load(this);
        _dependencies.InjectDependencies(this);
    }

    public void UpdateState(UtilityVendorBoundUserInterfaceState state)
    {
        BalanceLabel.Text = Loc.GetString("utility-vendor-ui-balance", ("points", state.Points));

        CategoryTabs.RemoveAllChildren();

        var sortedCategories = state.Categories.OrderBy(c => c.Priority).ToList();
        var allScrollContainer = new ScrollContainer();
        var allContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            VerticalExpand = true,
            HorizontalExpand = true
        };

        TabContainer.SetTabTitle(allScrollContainer, Loc.GetString("utility-vendor-ui-tab-all"));
        allScrollContainer.AddChild(allContainer);
        CategoryTabs.AddChild(allScrollContainer);

        PopulateAllCategory(allContainer, sortedCategories, state.Points);

        foreach (var category in sortedCategories)
        {
            var scrollContainer = new ScrollContainer();
            var categoryContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                VerticalExpand = true,
                HorizontalExpand = true
            };

            TabContainer.SetTabTitle(scrollContainer, Loc.GetString(category.Name));
            scrollContainer.AddChild(categoryContainer);
            CategoryTabs.AddChild(scrollContainer);

            PopulateCategoryContainer(categoryContainer, category.Inventory, state.Points);
        }
    }

    private void PopulateCategoryContainer(BoxContainer container, Dictionary<EntProtoId, FixedPoint2> inventory, FixedPoint2 points)
    {
        foreach (var (itemId, price) in inventory)
        {
            if (!_prototypeManager.TryIndex<EntityPrototype>(itemId, out var prototype))
                continue;

            var itemButton = new UtilityVendorItem(itemId, price, prototype.Name, prototype.Description);
            itemButton.OnPressed += _ => OnPurchase?.Invoke(itemId);
            itemButton.Disabled = points < price;

            container.AddChild(itemButton);
        }
    }

    private void PopulateAllCategory(BoxContainer container, List<CategoryData> categories, FixedPoint2 points)
    {
        var allItems = new Dictionary<EntProtoId, FixedPoint2>();
        foreach (var category in categories)
        {
            foreach (var (itemId, price) in category.Inventory)
            {
                if (!allItems.ContainsKey(itemId))
                    allItems[itemId] = price;
            }
        }

        PopulateCategoryContainer(container, allItems, points);
    }

    private sealed class UtilityVendorItem : PanelContainer
    {
        public event Action<BaseButton.ButtonEventArgs>? OnPressed;

        private static readonly Color DisabledColor = Color.FromHex("#444444");
        private static readonly Color EnabledColor = Color.FromHex("#2D2D30");
        private static readonly Color HoveredColor = Color.FromHex("#3A3A3E");
        private static readonly Color BorderColor = Color.FromHex("#4972A1");

        private readonly Button _button;
        private readonly StyleBoxFlat _styleBox;

        public bool Disabled
        {
            get => _button.Disabled;
            set
            {
                _button.Disabled = value;
                UpdateColor();
            }
        }

        public UtilityVendorItem(string itemId, FixedPoint2 price, string itemName, string itemDesc)
        {
            HorizontalExpand = true;
            MinSize = new Vector2(0, 80);
            Margin = new Thickness(0, 2);

            _styleBox = new StyleBoxFlat
            {
                BackgroundColor = EnabledColor,
                BorderColor = BorderColor,
                BorderThickness = new Thickness(1),
                ContentMarginTopOverride = 8,
                ContentMarginBottomOverride = 8,
                ContentMarginLeftOverride = 12,
                ContentMarginRightOverride = 12
            };
            PanelOverride = _styleBox;

            var mainContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalExpand = true
            };

            var iconContainer = new Control
            {
                MinSize = new Vector2(64, 64),
                HorizontalExpand = false,
                Margin = new Thickness(0, 0, 12, 0)
            };

            var entityView = new EntityPrototypeView
            {
                Scale = new Vector2(2f, 2f),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                OverrideDirection = Direction.South
            };
            entityView.SetPrototype(itemId);
            iconContainer.AddChild(entityView);

            var infoContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var nameLabel = new Label
            {
                Text = itemName,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 2)
            };

            infoContainer.AddChild(nameLabel);

            var priceContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = false,
                MinSize = new Vector2(80, 0),
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Right
            };

            var priceLabel = new Label
            {
                Text = $"{price}",
                HorizontalAlignment = HAlignment.Right,
                StyleClasses = { "LabelBig" },
                Margin = new Thickness(0, 0, 0, 2)
            };

            var pointsLabel = new Label
            {
                Text = Loc.GetString("utility-vendor-ui-points"),
                HorizontalAlignment = HAlignment.Right,
                StyleClasses = { "LabelSubText" }
            };

            priceContainer.AddChild(priceLabel);
            priceContainer.AddChild(pointsLabel);

            mainContainer.AddChild(iconContainer);
            mainContainer.AddChild(infoContainer);
            mainContainer.AddChild(priceContainer);

            _button = new Button
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                MouseFilter = MouseFilterMode.Stop,
                ToolTip = itemDesc,
                Children = { mainContainer }
            };

            _button.OnPressed += args => OnPressed?.Invoke(args);
            _button.OnMouseEntered += _ => UpdateColor();
            _button.OnMouseExited += _ => UpdateColor();

            AddChild(_button);
            UpdateColor();
        }

        private void UpdateColor()
        {
            if (_button.Disabled)
            {
                _styleBox.BackgroundColor = DisabledColor;
                _styleBox.BorderColor = Color.FromHex("#666666");
            }
            else
            {
                _styleBox.BackgroundColor = _button.IsHovered ? HoveredColor : EnabledColor;
                _styleBox.BorderColor = BorderColor;
            }
        }
    }
}
