using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Ninja.UI;

[GenerateTypedNameReferences]
public sealed partial class SuitActivationConfirmDialog : FancyWindow
{
    public event Action? OnConfirmed;

    public SuitActivationConfirmDialog()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ =>
        {
            OnConfirmed?.Invoke();
            Close();
        };

        CancelButton.OnPressed += _ => Close();
    }
}
