# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTLeader
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazineMagnum

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    neck: Whistle
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled # Corvax-Wega
    pocket1: WeaponPistolN1984 # Corvax-Wega
    pocket2: FlashlightSeclite # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazineMagnum
    - EmergencyMedipen

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGearArmed
  equipment:
    pocket2: WeaponDisabler # Corvax-Wega
    suitstorage: WeaponRifleLecterXL8 # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazineMagnum
    - EmergencyMedipen

- type: chameleonOutfit
  id: ERTLeaderChameleonOutfit
  job: ERTLeader
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTLeader
    neck: ClothingNeckBronzeheart

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGearEVA
  icon: "JobIconERTChaplain"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTChaplainGearEVA
  id: ERTChaplainGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatFez
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat # Corvax-Wega
    outerClothing: ClothingOuterArmorBasicSlim # Corvax-Wega
    id: ERTChaplainPDA # Corvax-Wega
    ears: ClothingHeadsetAltCentCom # Corvax-Wega
    belt: WeaponNullRodERT # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: DrinkWaterBottleFull # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - BoxCandle
    - DrinkWaterBottleFull # Corvax-Wega
    - DrinkWaterBottleFull # Corvax-Wega
    - HolyWaterGrenade # Corvax-Wega
    - HolyWaterGrenade # Corvax-Wega
    - HolyWaterGrenade # Corvax-Wega
    - Lantern
    - Lantern
    - Bible
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponNullRodERT # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: DrinkWaterBottleFull # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - BoxCandle
    - DrinkWaterBottleFull # Corvax-Wega
    - DrinkWaterBottleFull # Corvax-Wega
    - HolyWaterGrenade # Corvax-Wega
    - HolyWaterGrenade # Corvax-Wega
    - HolyWaterGrenade # Corvax-Wega
    - Lantern
    - Lantern
    - Bible
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter

- type: chameleonOutfit
  id: ERTChaplainChameleonOutfit
  job: ERTChaplain
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTChaplain
    mask: ClothingMaskGasERT
    outerClothing: ClothingOuterHardsuitERTChaplain
    shoes: ClothingShoesBootsMagAdv

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconERTEngineer"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesGlassesMeson # Corvax-Wega
    gloves: ClothingHandsGlovesCombat # Corvax-Wega
    outerClothing: ClothingOuterArmorBasicSlim # Corvax-Wega
    id: ERTEngineerPDA # Corvax-Wega
    ears: ClothingHeadsetAltCentCom # Corvax-Wega
    belt: ClothingBeltChiefEngineerFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: GasAnalyzer # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - trayScanner
    - CombatRCDExperimental # Corvax-Wega
    - BorgGeneratorMaterialSteal # Corvax-Wega
    - BorgGeneratorMaterialPlasteel # Corvax-Wega
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: GasAnalyzer # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - trayScanner
    - CombatRCDExperimental # Corvax-Wega
    - BorgGeneratorMaterialSteal # Corvax-Wega
    - BorgGeneratorMaterialPlasteel # Corvax-Wega
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - MetalFoamGrenade
    - AirGrenade

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGearArmed
  equipment:
    suitstorage: WeaponShotgunEnforcer
  storage:
    back:
    - RCD
    - GasAnalyzer
    - HolofanProjector
    - MiningDrillDiamond
    - BoxLethalshot
    - BoxShotgunSlug # End of first line
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - CableDetStack
    - BoxDetonator

- type: chameleonOutfit
  id: ERTEngineerChameleonOutfit
  job: ERTEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTEngineer
    neck: ClothingNeckEngineermedal

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTSecurityGearEVA
  icon: "JobIconERTSecurity"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTSecurity
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazinePistol # Corvax-Wega-ERT

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    neck: SecurityWhistle
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled # Corvax-Wega
    pocket2: FlashlightSeclite # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazinePistol # Corvax-Wega-ERT
    - EmergencyMedipen

- type: startingGear
  id: ERTSecurityGearArmedRifle
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity # Corvax-Wega
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - WeaponRifleLecter
    - MagazineRifle
    - MagazineRifle
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazinePistol # Corvax-Wega-ERT
    - EmergencyMedipen

- type: chameleonOutfit
  id: ERTSecurityChameleonOutfit
  job: ERTSecurity
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTSecurity
    neck: ClothingNeckSecuritymedal

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconERTMedic"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTMedicalGearEVA
  id: ERTMedicalGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudMedical # Corvax-Wega
    gloves: ClothingHandsGlovesLatexSurgeon # Corvax-Wega-Surgery
    outerClothing: ClothingOuterArmorBasicSlim # Corvax-Wega
    id: ERTMedicPDA # Corvax-Wega
    ears: ClothingHeadsetAltCentCom # Corvax-Wega
    belt: ClothingBeltMedicalFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: Hypospray # Corvax-Wega-ERT
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - SurgerykitFilledPro # Corvax-Wega-Surgery
    - SyringeBluespace # Corvax-Wega-ERT
    - MedkitAdvancedFilled # Corvax-Wega-ERT
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesLatexSurgeon # Corvax-Wega-Surgery
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: Hypospray # Corvax-Wega-ERT
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - SurgerykitFilledPro # Corvax-Wega-Surgery
    - SyringeBluespace # Corvax-Wega-ERT
    - MedkitCombatFilled
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine

- type: chameleonOutfit
  id: ERTMedicalChameleonOutfit
  job: ERTMedical
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTMedical
    neck: ClothingNeckStethoscope

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconERTJanitor"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTJanitorGearEVA
  id: ERTJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    gloves: ClothingHandsGlovesColorPurple # Corvax-Wega
    outerClothing: ClothingOuterArmorBasicSlim # Corvax-Wega
    id: ERTJanitorPDA # Corvax-Wega
    ears: ClothingHeadsetAltCentCom # Corvax-Wega
    belt: ClothingBeltJanitorFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: Holoprojector # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - LightReplacerBorg # Corvax-Wega
    - BoxTrashbag # Corvax-Wega
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - WeaponLauncherHydra
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - AdvMopItem

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: Holoprojector # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    - LightReplacerBorg # Corvax-Wega
    - BoxTrashbag # Corvax-Wega
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - WeaponLauncherHydra
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - GrenadeCleanade # Corvax-Wega
    - AdvMopItem

- type: chameleonOutfit
  id: ERTJanitorChameleonOutfit
  job: ERTJanitor
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTJanitor
    neck: ClothingNeckScarfStripedPurple
    eyes: ClothingEyesGlassesSunglasses
