# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconERTLeader"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - BlueShieldOfficer # Corwax-Wega-BSO-Access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, BluespaceLifelineImplant ] # Corvax-Wega-Add

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTLeader
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  # Corvax-Wega-ERT-start
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazineMagnum
  # Corvax-Wega-ERT-end

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingERTHud # Corvax-Wega-ERT
    neck: Whistle
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled # Corvax-Wega
    pocket1: WeaponPistolN1984 # Corvax-Wega
    pocket2: FlashlightSeclite # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    # Corvax-Wega-ERT-start
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazineMagnum
    - EmergencyMedipen
    # Corvax-Wega-ERT-end

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGearArmed
  equipment:
    pocket2: WeaponDisabler # Corvax-Wega
    suitstorage: WeaponRifleLecterXL8 # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    # Corvax-Wega-ERT-start
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazineMagnum
    - EmergencyMedipen
    # Corvax-Wega-ERT-end

- type: chameleonOutfit
  id: ERTLeaderChameleonOutfit
  job: ERTLeader
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTLeader
    neck: ClothingNeckBronzeheart

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGearEVA
  icon: "JobIconERTChaplain"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - BlueShieldOfficer # Corwax-Wega-BSO-Access
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, BluespaceLifelineImplant ] # Corvax-Wega-Add

- type: startingGear
  parent: ERTChaplainGearEVA
  id: ERTChaplainGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatFez
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterArmorBasicSlim # Corvax-Wega
    gloves: ClothingHandsGlovesCombat # Corvax-Wega
    id: ERTChaplainPDA # Corvax-Wega
    ears: ClothingHeadsetAltCentCom # Corvax-Wega
    belt: ClothingBeltSheathChaplinFilledERT # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: DrinkWaterBottleFull # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  # Corvax-Wega-ERT-start
  storage:
    back:
    - BoxCandle
    - DrinkWaterBottleFull
    - DrinkWaterBottleFull
    - HolyWaterGrenade
    - HolyWaterGrenade
    - HolyWaterGrenade
    - Lantern
    - Lantern
    - Bible
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter
  # Corvax-Wega-ERT-end

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingERTHud # Corvax-Wega-ERT
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSheathChaplinFilledERT # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: DrinkWaterBottleFull # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    # Corvax-Wega-ERT-start
    - BoxCandle
    - DrinkWaterBottleFull
    - DrinkWaterBottleFull
    - HolyWaterGrenade
    - HolyWaterGrenade
    - HolyWaterGrenade
    - Lantern
    - Lantern
    - Bible
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter
    # Corvax-Wega-ERT-end

- type: chameleonOutfit
  id: ERTChaplainChameleonOutfit
  job: ERTChaplain
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTChaplain
    mask: ClothingMaskGasERT
    outerClothing: ClothingOuterHardsuitERTChaplain
    shoes: ClothingShoesBootsMagAdv

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconERTEngineer"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - BlueShieldOfficer # Corwax-Wega-BSO-Access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, BluespaceLifelineImplant ] # Corvax-Wega-Add

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTEngineer
    outerClothing: ClothingOuterArmorBasicSlim # Corvax-Wega
    eyes: ClothingERTHud # Corvax-Wega-ERT
    gloves: ClothingHandsGlovesCombat # Corvax-Wega
    id: ERTEngineerPDA # Corvax-Wega
    ears: ClothingHeadsetAltCentCom # Corvax-Wega
    belt: ClothingBeltChiefEngineerFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: GasAnalyzer # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  # Corvax-Wega-ERT-start
  storage:
    back:
    - trayScanner
    - CombatRCDExperimental
    - BorgGeneratorMaterialSteal
    - BorgGeneratorMaterialPlasteel
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass
  # Corvax-Wega-ERT-end

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingERTHud # Corvax-Wega-ERT
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: GasAnalyzer # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    # Corvax-Wega-ERT-start
    - trayScanner
    - CombatRCDExperimental
    - BorgGeneratorMaterialSteal
    - BorgGeneratorMaterialPlasteel
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - MetalFoamGrenade
    - AirGrenade
    # Corvax-Wega-ERT-end

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGearArmed
  equipment:
    suitstorage: WeaponShotgunEnforcer
  storage:
    back:
    - RCD
    - GasAnalyzer
    - HolofanProjector
    - MiningDrillDiamond
    - BoxLethalshot
    - BoxShotgunSlug # End of first line
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - CableDetStack
    - BoxDetonator

- type: chameleonOutfit
  id: ERTEngineerChameleonOutfit
  job: ERTEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTEngineer
    neck: ClothingNeckEngineermedal

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTSecurityGearEVA
  icon: "JobIconERTSecurity"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - BlueShieldOfficer # Corwax-Wega-BSO-Access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, BluespaceLifelineImplant ] # Corvax-Wega-Add

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTSecurity
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  # Corvax-Wega-ERT-start
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazinePistol # Corvax-Wega-ERT
  # Corvax-Wega-ERT-end

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingERTHud # Corvax-Wega-ERT
    gloves: ClothingHandsGlovesCombat
    neck: SecurityWhistle
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled # Corvax-Wega
    pocket2: FlashlightSeclite # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    # Corvax-Wega-ERT-start
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazinePistol # Corvax-Wega-ERT
    - EmergencyMedipen
    # Corvax-Wega-ERT-end

- type: startingGear
  id: ERTSecurityGearArmedRifle
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity # Corvax-Wega
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingERTHud # Corvax-Wega-ERT
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled # Corvax-Wega
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    # Corvax-Wega-ERT-start
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - WeaponRifleLecter
    - MagazineRifle
    - MagazineRifle
    - CombatCrowbar # Corvax-Wega-CombatCrowbar
    - MagazinePistol # Corvax-Wega-ERT
    - EmergencyMedipen
    # Corvax-Wega-ERT-end

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedGrenade
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponLauncherHydraLethal
  storage:
    back:
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeFlash
    - GrenadeFlash # End of first line
    - GrenadeEMP
    - GrenadeEMP
    - GrenadeEMP
    - MagazinePistol
    - Truncheon
    belt:
    - Handcuffs
    - CrowbarRed
    - EmergencyMedipen
    - WeaponPistolMk58
    - MagazinePistol
    - MagazinePistol
    - MedkitCombatFilled

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedVanguard
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponSubMachineGunWt550
  storage:
    back:
    - ExGrenade
    - SmokeGrenade
    - EmpGrenade
    - TelescopicShield
    - TelescopicShield # End of first line
    - MedkitCombatFilled
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    - Truncheon
    belt:
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen
    - HoloprojectorSecurity

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedShotgun
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponShotgunEnforcer
  storage:
    back:
    - SmokeGrenade
    - BoxLethalshot
    - BoxShotgunSlug
    - BoxShotgunIncendiary
    - MedkitCombatFilled # End of first line
    - ExGrenade
    - CableDetStack
    - BoxDetonator
    - Truncheon
    belt:
    - Handcuffs
    - Handcuffs
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: chameleonOutfit
  id: ERTSecurityChameleonOutfit
  job: ERTSecurity
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTSecurity
    neck: ClothingNeckSecuritymedal

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconERTMedic"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - BlueShieldOfficer # Corwax-Wega-BSO-Access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, BluespaceLifelineImplant ] # Corvax-Wega-Add

- type: startingGear
  parent: ERTMedicalGearEVA
  id: ERTMedicalGear
  equipment:
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHelmetERTMedic
    outerClothing: ClothingOuterArmorBasicSlim # Corvax-Wega
    eyes: ClothingERTHud # Corvax-Wega-ERT
    gloves: ClothingHandsGlovesLatexSurgeon # Corvax-Wega-Surgery
    id: ERTMedicPDA # Corvax-Wega
    ears: ClothingHeadsetAltCentCom # Corvax-Wega
    belt: ClothingBeltMedicalFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: Hypospray # Corvax-Wega-ERT
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  # Corvax-Wega-ERT-start
  storage:
    back:
    - SurgerykitFilledPro
    - SyringeBluespace
    - MedkitAdvancedFilled
    - CombatCrowbar
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine
  # Corvax-Wega-ERT-end

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagCombat # Corvax-Wega-MagCombat
    mask: ClothingMaskGasERT
    eyes: ClothingERTHud # Corvax-Wega-ERT
    gloves: ClothingHandsGlovesLatexSurgeon # Corvax-Wega-Surgery
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled # Corvax-Wega
    pocket1: WeaponPistolMk58 # Corvax-Wega
    pocket2: Hypospray # Corvax-Wega-ERT
    underwearbottom: ClothingUnderBottomHearts # Corvax-Wega
  storage:
    back:
    # Corvax-Wega-ERT-start
    - SurgerykitFilledPro
    - SyringeBluespace
    - MedkitCombatFilled
    - CombatCrowbar
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine
    # Corvax-Wega-ERT-end

- type: startingGear
  parent: ERTMedicalGearEVA
  id: ERTMedicalGearArmed
  equipment:
    suitstorage: WeaponRifleLecter
    pocket2: WeaponDisabler
  storage:
    back:
    - Hypospray
    - JugPunctTranex
    - JugPyraDerma
    - JugDexPlusSaline
    - JugTrico # End of first line
    - BeakerSmallArith
    - DefibrillatorCompact
    - MedkitCombatFilled
    - ClothingEyesGlassesChemical
    - ChemistryBottleOmnizine
    - Truncheon
    belt:
    - Zipties
    - CrowbarRed
    - MagazineRifle
    - MagazineRifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium # End of first line
    - Zipties

- type: chameleonOutfit
  id: ERTMedicalChameleonOutfit
  job: ERTMedical
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTMedical
    neck: ClothingNeckStethoscope

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconERTJanitor"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  - BlueShieldOfficer # Corwax-Wega-BSO-Access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm, BluespaceLifelineImplant ] # Corvax-Wega-Add

- type: startingGear
  parent: ERTJanitorGearEVA
  id: ERTJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    outerClothing: ClothingOuterArmorBasic
    pocket2: FlashlightSeclite

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
    suitstorage: WeaponLauncherHydra
  storage:
    back:
    - SoapNT
    - Plunger
    - Screwdriver
    - AdvMopItem
    - GrenadeCleanade
    - GrenadeCleanade # End of first line
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    belt:
    - MegaSprayBottleSpaceCleaner
    - Holoprojector
    - LightReplacerFilled
    - WireBrush
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen
  inhand:
  - TrashBag

- type: chameleonOutfit
  id: ERTJanitorChameleonOutfit
  job: ERTJanitor
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTJanitor
    neck: ClothingNeckScarfStripedPurple
    eyes: ClothingERTHud # Corvax-Wega-ERT
