// Developed by Nox project.
// Author: KloopRe

using Content.Shared._Modifications.Disease;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Modifications.Disease.UI;

[GenerateTypedNameReferences]
public sealed partial class DiseaseAnalyzerControl : BoxContainer
{
    public DiseaseAnalyzerControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(DiseaseAnalyzerUiState state)
    {
        if (!state.IsInfected)
        {
            StatusLabel.Text = Loc.GetString("disease-analyzer-not-infected");
            InfoPanel.Visible = false;
            return;
        }

        StatusLabel.Text = Loc.GetString("disease-analyzer-infected");
        InfoPanel.Visible = true;

        StrainLabel.Text = Loc.GetString("disease-analyzer-strain", ("id", state.StrainId ?? "???"));
        CureProgressLabel.Text = Loc.GetString("disease-analyzer-cure-progress", ("progress", (state.CureProgress * 100f).ToString("F1")));
        SymptomCountLabel.Text = Loc.GetString("disease-analyzer-symptom-count", ("count", state.SymptomCount));
    }
}
