// Developed by Nox project.
// Author: KloopRe

using Content.Client.UserInterface.Controls;
using Content.Shared._Modifications.Disease;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Modifications.Disease.UI;

[GenerateTypedNameReferences]
public sealed partial class DiseaseAnalyzerWindow : FancyWindow
{
    public DiseaseAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(DiseaseAnalyzerScannedMessage msg)
    {
        DiseaseAnalyzer.Populate(msg.State);
    }
}
