using System.Numerics;
using System.Text;
using System.Text.RegularExpressions;
using Content.Client.UserInterface.Controls;
using Content.Shared.Actions.Components;
using Content.Shared.Vampire;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Wega.Vampire.Ui;

[GenerateTypedNameReferences]
public sealed partial class TrophiesMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private static readonly Dictionary<BestiaOrganType, EntProtoId> DefaultOrganProto = new()
    {
        { BestiaOrganType.Heart, "OrganHumanHeart" },
        { BestiaOrganType.Lungs, "OrganHumanLungs" },
        { BestiaOrganType.Liver, "OrganHumanLiver" },
        { BestiaOrganType.Kidneys, "OrganHumanKidneys" },
        { BestiaOrganType.Eyes, "OrganHumanEyes" },
        { BestiaOrganType.Stomach, "OrganHumanStomach" }
    };

    private static readonly Regex ColorTagRegex = new Regex(
        @"\[color=[^\]]+\]|\[/color\]",
        RegexOptions.Compiled | RegexOptions.CultureInvariant
    );

    public TrophiesMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
    }

    public void Populate(TrophiesEuiState state)
    {
        OrganGrid.RemoveAllChildren();
        foreach (var organ in state.Organs)
        {
            var widget = CreateOrganWidget(organ);
            OrganGrid.AddChild(widget);
        }

        PassiveGrid.RemoveAllChildren();
        foreach (var bonus in state.PassiveBonuses)
        {
            var label = new Label
            {
                Text = $"{bonus.Name}: {bonus.Value}" + (bonus.IsMaxed ? $" {Loc.GetString($"vampire-trophies-ui-max")}" : ""),
                HorizontalExpand = true,
                Margin = new Thickness(0, 2)
            };
            if (bonus.ValueColor != null) label.ModulateSelfOverride = bonus.ValueColor.Value;
            PassiveGrid.AddChild(label);
        }

        AbilitiesContainer.RemoveAllChildren();
        foreach (var ability in state.Abilities)
        {
            var button = new TextureButton
            {
                ToolTip = BuildTooltip(ability),
                Scale = new Vector2(3f, 3f),
                VerticalExpand = true,
                Margin = new Thickness(5)
            };

            var entity = _entityManager.GetEntity(ability.Action);
            if (_entityManager.TryGetComponent<ActionComponent>(entity, out var action) && action.Icon != null)
                button.TextureNormal = _spriteSystem.Frame0(action.Icon);

            AbilitiesContainer.AddChild(button);
        }
    }

    private Control CreateOrganWidget(OrganDisplayInfo organ)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalExpand = true,
            Margin = new Thickness(5)
        };

        var iconProto = DefaultOrganProto.GetValueOrDefault(organ.Type, "OrganHumanHeart");

        string? actualProto = null;
        if (organ.PreviewEntity != null)
        {
            var entity = _entityManager.GetEntity(organ.PreviewEntity.Value);
            if (_entityManager.TryGetComponent<MetaDataComponent>(entity, out var meta))
                actualProto = meta.EntityPrototype?.ID;
        }
        if (string.IsNullOrEmpty(actualProto))
            actualProto = iconProto;

        var icon = new EntityPrototypeView
        {
            Scale = new Vector2(2f, 2f),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 0, 2)
        };
        icon.SetPrototype(actualProto);

        var countLabel = new Label
        {
            Text = $"{organ.Count}/{organ.MaxCount}"
                + $"\n{Loc.GetString($"vampire-bestia-{organ.Type.ToString().ToLower()}").ToUpper()}",
            Align = Label.AlignMode.Center,
            HorizontalExpand = true,
            ModulateSelfOverride = organ.CountColor
        };

        container.AddChild(icon);
        container.AddChild(countLabel);
        return container;
    }

    private string BuildTooltip(AbilityDisplayInfo ability)
    {
        var sb = new StringBuilder();

        var cleanName = ColorTagRegex.Replace(ability.Name, string.Empty);

        sb.AppendLine(cleanName);
        sb.AppendLine();

        if (ability.Bonuses.Count == 0)
        {
            sb.AppendLine(Loc.GetString("vampire-trophies-ui-no-bonuses"));
        }
        else
        {
            foreach (var bonus in ability.Bonuses)
            {
                var maxTag = bonus.IsMaxed ? $" {Loc.GetString($"vampire-trophies-ui-max")}" : "";
                sb.AppendLine($"• {bonus.OrganType}: {bonus.Description}{maxTag}");
            }
        }

        return sb.ToString();
    }
}
