using Content.Client.UserInterface.Controls;
using Content.Shared.Vampire;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.Vampire.Ui;

[GenerateTypedNameReferences]
public sealed partial class VampireClassSelectionMenu : RadialMenu
{
    public event Action<VampireClassEnum>? OnClassSelected;

    public VampireClassSelectionMenu()
    {
        RobustXamlLoader.Load(this);

        HemomancerButton.OnButtonUp += _ => OnClassSelected?.Invoke(VampireClassEnum.Hemomancer);
        UmbraeButton.OnButtonUp += _ => OnClassSelected?.Invoke(VampireClassEnum.Umbrae);
        GargantuaButton.OnButtonUp += _ => OnClassSelected?.Invoke(VampireClassEnum.Gargantua);
        DantalionButton.OnButtonUp += _ => OnClassSelected?.Invoke(VampireClassEnum.Dantalion);
        BestiaButton.OnButtonUp += _ => OnClassSelected?.Invoke(VampireClassEnum.Bestia);
    }
}
