- type: antag
  id: BloodBrother
  name: roles-antag-bloodbrother-name
  antagonist: true
  setPreference: true
  objective: roles-antag-bloodbrother-objective
  guides: [ BloodBrothers ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 50h # Corvax-RoleTime
  - !type:DepartmentTimeRequirement
    department: Security
    time: 25h

- type: antagSpecifier
  parent: RestrictedAntag
  id: BloodBrother
  prefRoles:
  - BloodBrother
  allowNonHumans: true
  multiAntagSetting: None
  blacklist:
    components:
    - AntagImmune
    - Pacified # Diona ha-ha-ha
  mindRoles:
  - MindRoleBloodBrother
  briefing:
    sound: "/Audio/Misc/thief_greeting.ogg"
