## Recipes

# Clothing

- type: latheRecipe
  id: PortableRechargerBag
  result: PortableRechargerBag
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 1500
    Plastic: 750
    Plasma: 500
    Gold: 300
    Silver: 150
    Glass: 500

- type: latheRecipe
  id: PortableRechargerTurbo
  result: PortableRechargerTurbo
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 1500
    Plastic: 750
    Plasma: 500
    Gold: 300
    Silver: 150
    Glass: 500

- type: latheRecipe
  id: PortableRechargerTurboBag
  result: PortableRechargerTurboBag
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2500
    Plastic: 1500
    Plasma: 1000
    Glass: 500
    Uranium: 150
    Gold: 500
    Silver: 300

- type: latheRecipe
  id: ClothingHeadHelmetFlash
  result: ClothingHeadHelmetFlash
  categories:
  - Clothing
  completetime: 5
  materials:
    Steel: 350
    Plastic: 200
    Plasma: 100
    Gold: 25
    Glass: 150

- type: latheRecipe
  id: ClothingNeckFlashNeck
  result: ClothingNeckFlashNeck
  categories:
  - Clothing
  completetime: 3
  materials:
    Steel: 400
    Plastic: 300
    Plasma: 300
    Glass: 200
    Uranium: 25
    
# Tools

- type: latheRecipe
  parent: BaseToolRecipe
  id: ExmFlash
  result: ExmFlash
  materials:
    Steel: 200
    Glass: 100
    Plastic: 200
    Plasma: 50
