- type: entity
  id: BaseStationLavaland
  abstract: true
  components:
    - type: StationLavaland
      biome: Lavaland
    - type: StationLavalandShuttle
    - type: StationLavalandPenalServitudeShuttle
