- type: entity
  id: BaseStationLavaland
  abstract: true
  components:
    - type: StationLavaland
      planets: [ Lavaland, Icemoon ]
    - type: StationLavalandShuttle
    - type: StationLavalandPenalServitudeShuttle
