using System.Linq;
using Content.Client.Botany.Systems;
using Content.Client.UserInterface.Controls;
using Content.Shared.Botany.PlantAnalyzer;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Wega.Botany;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerWindow : FancyWindow
{
    private readonly EntityManager _entityManager;
    private readonly IGameTiming _gameTiming;
    private readonly PlantAnalyzerSystem _plant;

    public PlantAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<EntityManager>();
        _gameTiming = dependencies.Resolve<IGameTiming>();
        _plant = _entityManager.System<PlantAnalyzerSystem>();
    }

    public void Populate(PlantAnalyzerScannedUserMessage msg)
    {
        Print.Disabled = !msg.ScanMode.GetValueOrDefault(false)
            || msg.PrintReadyAt.GetValueOrDefault(TimeSpan.MaxValue) > _gameTiming.CurTime
            || msg.PlantData is null;

        var target = _entityManager.GetEntity(msg.TargetEntity);

        // Header Section
        SpriteView.SetEntity(target);
        SpriteView.Visible = msg.ScanMode.HasValue && msg.ScanMode.Value;
        NoDataIcon.Visible = !SpriteView.Visible;

        ScanModeLabel.Text = msg.ScanMode.HasValue
            ? msg.ScanMode.Value
                ? Loc.GetString("plant-analyzer-scan-active")
                : Loc.GetString("plant-analyzer-scan-inactive")
            : Loc.GetString("plant-analyzer-no-data");

        ScanModeLabel.Modulate = msg.ScanMode.HasValue && msg.ScanMode.Value
            ? Color.FromHex("#4CAF50")
            : Color.FromHex("#F44336");

        SeedLabel.Text = msg.PlantData == null
            ? Loc.GetString("plant-analyzer-no-plant")
            : Loc.GetString(msg.PlantData.SeedDisplayName);

        ContainerLabel.Text = target != null && _entityManager.HasComponent<MetaDataComponent>(target.Value)
            ? Identity.Name(target.Value, _entityManager)
            : Loc.GetString("plant-analyzer-unknown-container");

        // Plant Status Tags
        if (msg.PlantData is not null)
        {
            Dead.Visible = msg.PlantData.Dead;
            Alive.Visible = !Dead.Visible;
            Unviable.Visible = !msg.PlantData.Viable;
            Kudzu.Visible = msg.PlantData.Kudzu;
            Mutating.Visible = msg.PlantData.Mutating;

            Alive.Modulate = Color.Green;
            Dead.Modulate = Color.Red;
            Unviable.Modulate = Color.Red;
            Mutating.Modulate = Color.Violet;
            Kudzu.Modulate = Color.Red;

            PlantDataTags.Visible = true;
        }
        else
        {
            PlantDataTags.Visible = false;
        }

        // Plant Health Stats
        if (msg.PlantData is not null)
        {
            Health.Text = msg.PlantData.Health.ToString("0.0");
            Endurance.Text = msg.PlantData.Endurance.ToString("0.0");
            Age.Text = msg.PlantData.Age.ToString("0.0");
            Lifespan.Text = msg.PlantData.Lifespan.ToString("0.0");
            Maturation.Text = msg.PlantData.Maturation.ToString("0.0");

            PlantDataGrid.Visible = true;
        }
        else
        {
            PlantDataGrid.Visible = false;
        }
        PlantDataDivider.Visible = PlantDataGrid.Visible;

        // Tray Conditions
        if (msg.TrayData is not null)
        {
            WaterLevelLabel.Text = msg.TrayData.WaterLevel.ToString("0.0");
            NutritionLevelLabel.Text = msg.TrayData.NutritionLevel.ToString("0.0");
            ToxinsLabel.Text = msg.TrayData.Toxins.ToString("0.0");
            PestLevelLabel.Text = msg.TrayData.PestLevel.ToString("0.1");
            WeedLevelLabel.Text = msg.TrayData.WeedLevel.ToString("0.1");

            // Set consumption/resistance indicators
            if (msg.TolerancesData is not null)
            {
                WaterConsumptionLabel.Text = $"→{msg.TolerancesData.WaterConsumption:0.0}";
                NutritionConsumptionLabel.Text = $"→{msg.TolerancesData.NutrientConsumption:0.0}";
                ToxinsResistanceLabel.Text = $"←{msg.TolerancesData.ToxinsTolerance:0.0}";
                PestResistanceLabel.Text = $"←{msg.TolerancesData.PestTolerance:0.1}";
                WeedResistanceLabel.Text = $"←{msg.TolerancesData.WeedTolerance:0.1}";
            }
            else
            {
                WaterConsumptionLabel.Text = "→?";
                NutritionConsumptionLabel.Text = "→?";
                ToxinsResistanceLabel.Text = "←?";
                PestResistanceLabel.Text = "←?";
                WeedResistanceLabel.Text = "←?";
            }

            ContainerGrid.Visible = true;
        }
        else
        {
            ContainerGrid.Visible = false;
        }
        ContainerDivider.Visible = ContainerGrid.Visible;

        // Soil Chemicals
        if (msg.TrayData?.Chemicals != null && msg.TrayData.Chemicals.Any())
        {
            var chemicals = _plant.ChemicalsToLocalizedStrings(msg.TrayData.Chemicals);
            ChemicalsInWaterLabel.Text = chemicals;
            ChemicalsInWaterBox.Visible = true;
        }
        else
        {
            ChemicalsInWaterBox.Visible = false;
        }
        ChemicalsInWaterDivider.Visible = ChemicalsInWaterBox.Visible;

        // Ideal Environment
        if (msg.TolerancesData is not null)
        {
            var environmentText = GenerateEnvironmentText(msg.TolerancesData);
            EnvironmentLabel.SetMessage(environmentText);
            EnvironmentBox.Visible = true;
        }
        else
        {
            EnvironmentBox.Visible = false;
        }
        EnvironmentDivider.Visible = EnvironmentBox.Visible;

        // Plant Output
        if (msg.ProduceData is not null)
        {
            var outputText = GenerateOutputText(msg.ProduceData);
            ProduceLabel.SetMessage(outputText);
            ProduceBox.Visible = true;
        }
        else
        {
            ProduceBox.Visible = false;
        }
        ProduceDivider.Visible = ProduceBox.Visible;
    }

    private FormattedMessage GenerateEnvironmentText(PlantAnalyzerTolerancesData data)
    {
        var msg = new FormattedMessage();

        // Temperature
        msg.AddText($"{Loc.GetString("plant-analyzer-temperature")}: ");
        msg.PushColor(Color.LightSkyBlue);
        msg.AddText($"{data.IdealHeat:0.0}°C ±{data.HeatTolerance:0.0}°C\n");
        msg.Pop();

        // Pressure
        msg.AddText($"{Loc.GetString("plant-analyzer-pressure")}: ");
        msg.PushColor(Color.LightGreen);
        msg.AddText($"{data.IdealPressure:0.0} kPa ±{data.PressureTolerance:0.0} kPa\n");
        msg.Pop();

        // Light
        msg.AddText($"{Loc.GetString("plant-analyzer-light")}: ");
        msg.PushColor(Color.Gold);
        msg.AddText($"{data.IdealLight:0.0} L ±{data.LightTolerance:0.0} L\n");
        msg.Pop();

        // Gases
        if (data.ConsumeGasses.Any())
        {
            msg.AddText($"{Loc.GetString("plant-analyzer-required-gases")}: ");
            msg.PushColor(Color.Plum);
            msg.AddText(_plant.GasesToLocalizedStrings(data.ConsumeGasses));
            msg.Pop();
        }

        return msg;
    }

    private FormattedMessage GenerateOutputText(PlantAnalyzerProduceData data)
    {
        var msg = new FormattedMessage();

        // Yield
        msg.AddText($"{Loc.GetString("plant-analyzer-yield")}: ");
        msg.PushColor(data.Yield > 0 ? Color.LightGreen : Color.LightGray);
        msg.AddText($"{data.Yield}\n");
        msg.Pop();

        // Potency
        msg.AddText($"{Loc.GetString("plant-analyzer-potency")}: ");
        msg.PushColor(Color.Gold);
        msg.AddText($"{Loc.GetString(data.Potency)}\n");
        msg.Pop();

        // Produce
        if (data.Produce.Any())
        {
            var (_, plural, _) = _plant.ProduceToLocalizedStrings(data.Produce);
            msg.AddText($"{Loc.GetString("plant-analyzer-produces")}: ");
            msg.PushColor(Color.LightBlue);
            msg.AddText($"{plural}\n");
            msg.Pop();
        }

        // Chemicals
        if (data.Chemicals.Any())
        {
            msg.AddText($"{Loc.GetString("plant-analyzer-chemicals")}: ");
            msg.PushColor(Color.MediumPurple);
            msg.AddText(_plant.ChemicalsToLocalizedStrings(data.Chemicals) + "\n");
            msg.Pop();
        }

        // Gases
        if (data.ExudeGasses.Any())
        {
            msg.AddText($"{Loc.GetString("plant-analyzer-exudes")}: ");
            msg.PushColor(Color.LightCoral);
            msg.AddText(_plant.GasesToLocalizedStrings(data.ExudeGasses) + "\n");
            msg.Pop();
        }

        // Seed info
        msg.AddText($"{Loc.GetString("plant-analyzer-seeds")}: ");
        msg.PushColor(data.Seedless ? Color.Orange : Color.LightGreen);
        msg.AddText(data.Seedless ?
            Loc.GetString("plant-analyzer-seedless") :
            Loc.GetString("plant-analyzer-produces-seeds"));
        msg.Pop();

        return msg;
    }
}
