using Content.Client.UserInterface.Controls;
using Content.Shared._Wega.SPAI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.SPAI;

[GenerateTypedNameReferences]
public sealed partial class SpaiChemInjectorWindow : FancyWindow
{
    public event Action<string, int>? OnInjectPressed;

    public SpaiChemInjectorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(SpaiChemInjectorBoundUserInterfaceState state)
    {
        EnergyLabel.Text = Loc.GetString("spai-injector-window-energy", ("current", state.Energy), ("max", state.EnergyMax));

        ReagentGrid.Children.Clear();
        foreach (var reagent in state.Reagents)
        {
            var btn = new Button
            {
                Text = Loc.GetString("spai-injector-window-reagent-button", ("name", reagent.LocalizedName), ("cost", reagent.EnergyCost)),
                Disabled = state.Energy < reagent.EnergyCost,
                HorizontalExpand = true,
                Margin = new Thickness(2),
            };
            var id = reagent.ReagentId;
            var cost = reagent.EnergyCost;
            btn.OnPressed += _ => OnInjectPressed?.Invoke(id, cost);
            ReagentGrid.Children.Add(btn);
        }
    }
}
