using Content.Client.Humanoid;
using Content.Shared.CCVar;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._Wega.Android.Ui;

[GenerateTypedNameReferences]
public sealed partial class AndroidConstructMenu : BaseWindow
{
    public HumanoidCharacterProfile? Profile;
    private MarkingsViewModel _markingsModel = new();

    public event Action<HumanoidCharacterProfile, bool>? ProfileChangedAction;
    public event Action? AssembleAttemptAction;

    private ColorSelectorSliders _colorSelect;

    private int _maxNameLength = 0;

    public AndroidConstructMenu()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        AssembleButton.OnPressed += _ => OnAssembleButtonPressed();

        Markings.SetModel(_markingsModel);

        NameEdit.OnTextChanged += args => OnNameChanged(args.Text);
        NameEdit.IsValid = args => args.Length <= _maxNameLength;

        SexButton.OnItemSelected += args => OnSexChanged((Sex)(args.Id));

        RgbSkinColorContainer.AddChild(_colorSelect = new ColorSelectorSliders());
        _colorSelect.SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv;
        _colorSelect.OnColorChanged += _ => OnSkinColorChanged();

        _markingsModel.MarkingsChanged += (_, _) => OnMarkingsChanged();

        UpdateSlotsStatus(false, false);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    public void LoadProfile(
        HumanoidCharacterProfile profile,
        IConfigurationManager cfgManager,
        MarkingManager markingManager,
        IPrototypeManager prototypeManager)
    {
        Profile = profile;

        _markingsModel.OrganData = markingManager.GetMarkingData(Profile.Species);
        _markingsModel.OrganProfileData = markingManager.GetProfileData(Profile.Species, Profile.Sex, Profile.Appearance.SkinColor, Profile.Appearance.EyeColor);
        _markingsModel.Markings = Profile.Appearance.Markings;

        _colorSelect.Color = Profile.Appearance.SkinColor;

        _maxNameLength = cfgManager.GetCVar(CCVars.MaxNameLength);
        NameEdit.Text = Profile.Name;

        UpdateSexControls(prototypeManager);
        UpdatePreview();
    }

    public void UpdateSlotsStatus(bool hasBattery, bool hasBrain)
    {
        var trueColor = Color.FromHex("#8fc032");
        var falseColor = Color.FromHex("#d83a46");

        BatteryStatusPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = hasBattery ? trueColor : falseColor };
        BatteryStatusText.Text = Loc.GetString("android-construct-ui-battery-label-" + hasBattery.ToString().ToLower());

        BrainStatusPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = hasBrain ? trueColor : falseColor };
        BrainStatusText.Text = Loc.GetString("android-construct-ui-brain-label-" + hasBrain.ToString().ToLower());
    }

    private void OnNameChanged(string newName)
    {
        if (Profile == null)
            return;

        Profile = Profile.WithName(newName);
        ProfileChangedAction?.Invoke(Profile, false);
    }

    private void OnSexChanged(Sex args)
    {
        if (Profile == null)
            return;

        SexButton.SelectId((int)args);
        Profile = Profile.WithSex(args);
        ProfileChangedAction?.Invoke(Profile, true);
    }

    private void UpdateSexControls(IPrototypeManager prototypeManager)
    {
        if (Profile == null)
            return;

        SexButton.Clear();

        var sexes = new List<Sex>();

        if (prototypeManager.Resolve(Profile.Species, out var speciesProto))
        {
            foreach (var sex in speciesProto.Sexes)
                sexes.Add(sex);
        }
        else
            sexes.Add(Sex.Unsexed);

        foreach (var sex in sexes)
            SexButton.AddItem(Loc.GetString($"humanoid-profile-editor-sex-{sex.ToString().ToLower()}-text"), (int)sex);

        if (sexes.Contains(Profile.Sex))
            SexButton.SelectId((int)Profile.Sex);
        else
            SexButton.SelectId((int)sexes[0]);
    }

    public void UpdatePreview()
    {
        if (Profile == null)
            return;

        SpritePreview.LoadPreview(Profile, null, false);
    }

    private void OnMarkingsChanged()
    {
        if (Profile == null)
            return;

        Profile.Appearance.Markings = _markingsModel.Markings;
        ProfileChangedAction?.Invoke(Profile, false);
    }

    private void OnSkinColorChanged()
    {
        if (Profile == null)
            return;

        Profile.Appearance.SkinColor = _colorSelect.Color;
        ProfileChangedAction?.Invoke(Profile, false);
    }

    private void OnAssembleButtonPressed()
    {
        AssembleAttemptAction?.Invoke();
    }
}
