name: YAML Linter

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: YAML Linter
    if: github.actor != 'IanComradeBot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      # Corvax-Secrets-Start
      - name: Setup secrets
        env:
          SSH_KEY: ${{ secrets.SECRETS_PRIVATE_KEY }}
        if: ${{ env.SSH_KEY != '' }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRETS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "HOST *" > ~/.ssh/config
          echo "  Hostname github.com" >> ~/.ssh/config
          echo "  Port 22" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          git clone git@github.com:corvax-nexus/secrets.git Secrets
          cp -R Secrets/Resources/Prototypes Resources/Prototypes/CorvaxSecrets
          cp -R Secrets/Resources/ServerPrototypes Resources/Prototypes/CorvaxSecretsServer
          cp -R Secrets/Resources/Locale Resources/Locale/ru-RU/corvax-secrets
          cp -R Secrets/Resources/Textures Resources/Textures/CorvaxSecrets
          cp -R Secrets/Resources/Audio Resources/Audio/CorvaxSecrets
      # Corvax-Secrets-End
      - name: Setup submodule
        run: |
          git submodule update --init --recursive
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 10.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      - name: Run Linter
        run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
